### ISSUE TITLE
LitElement API change

### ISSUE THREAD

**Issue by aadamsx** [GermanMtzmx/prism-markdown-element#1]
The LitElement API has change a lot since your last update.

**Comment by GermanMtzmx** [comment]
OK i keep in mind  and i will update the element asap :+1:

**Comment by GermanMtzmx** [comment]
The element has been updated to the latest lit-element api and should work properly using [V1.0.7](https://github.com/GermanMtzmx/prism-markdown-element/tree/v1.0.7)
